# Generated by Django 3.2.4 on 2021-06-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='product',
        ),
    ]
