# Generated by Django 3.2.4 on 2021-07-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
